"""initial schema

Revision ID: 62bd04b2fe33
Revises: 
Create Date: 2026-07-27 13:49:35.268849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '62bd04b2fe33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERIENCED', name='experience_level'), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('businesses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'BUILDING', 'OPERATING', 'GROWING', name='business_stage'), nullable=False),
    sa.Column('business_type', sa.Enum('ECOMMERCE', 'SERVICE', 'DIGITAL_PRODUCT', 'SAAS', 'OTHER', name='business_type'), nullable=False),
    sa.Column('primary_goal', sa.Enum('START_FIRST_BUSINESS', 'INCREASE_REVENUE', 'IMPROVE_ORGANIZATION', 'SCALE_OPERATIONS', name='primary_goal'), nullable=False),
    sa.Column('available_time_per_week', sa.Integer(), nullable=True),
    sa.Column('budget_range', sa.Enum('UNDER_1K', 'ONE_TO_FIVE_K', 'FIVE_TO_TWENTY_K', 'TWENTY_K_PLUS', name='budget_range'), nullable=True),
    sa.Column('current_challenges', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_user_id'), 'businesses', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='conversation_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_type', sa.Enum('ASSISTANT_CHAT', 'BUSINESS_BUILDER', 'CEO_BRIEFING', 'HEALTH_SCORE', name='conversation_context'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_business_id'), 'ai_conversations', ['business_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_created_at'), 'ai_conversations', ['created_at'], unique=False)
    op.create_table('ai_insights',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.Enum('CEO_BRIEFING', 'PATTERN', 'RECOMMENDATION', 'WARNING', name='insight_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='insight_priority'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_business_id'), 'ai_insights', ['business_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_generated_at'), 'ai_insights', ['generated_at'], unique=False)
    op.create_table('business_goals',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='goal_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_goals_business_id'), 'business_goals', ['business_id'], unique=False)
    op.create_table('business_plans',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('overview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='business_plan_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_plans_business_id'), 'business_plans', ['business_id'], unique=False)
    op.create_table('health_scores',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.SmallInteger(), nullable=False),
    sa.Column('revenue_score', sa.SmallInteger(), nullable=False),
    sa.Column('operations_score', sa.SmallInteger(), nullable=False),
    sa.Column('marketing_score', sa.SmallInteger(), nullable=False),
    sa.Column('customer_growth_score', sa.SmallInteger(), nullable=False),
    sa.Column('financial_management_score', sa.SmallInteger(), nullable=False),
    sa.Column('ai_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_scores_business_id'), 'health_scores', ['business_id'], unique=False)
    op.create_index(op.f('ix_health_scores_calculated_at'), 'health_scores', ['calculated_at'], unique=False)
    op.create_table('memory_records',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.Enum('FACT', 'DECISION', 'PREFERENCE', 'COMPLETED_MILESTONE', 'NOTE', name='memory_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('ONBOARDING', 'ASSISTANT_CHAT', 'BUSINESS_BUILDER', 'USER_MANUAL', 'SYSTEM_INFERRED', name='memory_source'), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_business_id'), 'memory_records', ['business_id'], unique=False)
    op.create_index(op.f('ix_memory_records_created_at'), 'memory_records', ['created_at'], unique=False)
    op.create_table('projects',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'COMPLETED', name='project_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_business_id'), 'projects', ['business_id'], unique=False)
    op.create_table('revenue_entries',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_entries_business_id'), 'revenue_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_revenue_entries_entry_date'), 'revenue_entries', ['entry_date'], unique=False)
    op.create_table('tasks',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='task_priority'), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'SKIPPED', name='task_status'), nullable=False),
    sa.Column('source', sa.Enum('USER_CREATED', 'AI_GENERATED', name='task_source'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['business_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_business_id'), 'tasks', ['business_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_business_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_revenue_entries_entry_date'), table_name='revenue_entries')
    op.drop_index(op.f('ix_revenue_entries_business_id'), table_name='revenue_entries')
    op.drop_table('revenue_entries')
    op.drop_index(op.f('ix_projects_business_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_memory_records_created_at'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_business_id'), table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index(op.f('ix_health_scores_calculated_at'), table_name='health_scores')
    op.drop_index(op.f('ix_health_scores_business_id'), table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index(op.f('ix_business_plans_business_id'), table_name='business_plans')
    op.drop_table('business_plans')
    op.drop_index(op.f('ix_business_goals_business_id'), table_name='business_goals')
    op.drop_table('business_goals')
    op.drop_index(op.f('ix_ai_insights_generated_at'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_business_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_ai_conversations_created_at'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_business_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_businesses_user_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
