"""add business_profiles table

Revision ID: 71761b9a3cf2
Revises: 25c1ffd4698b
Create Date: 2026-08-18 16:56:07.513794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71761b9a3cf2'
down_revision: Union[str, None] = '25c1ffd4698b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('products_services', sa.Text(), nullable=True),
    sa.Column('target_customers', sa.Text(), nullable=True),
    sa.Column('company_goals', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_business_id'), 'business_profiles', ['business_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_profiles_business_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
