"""initial schema

Revision ID: 71e3f3d78bdc
Revises: 62bd04b2fe33
Create Date: 2026-07-27 19:40:59.011136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71e3f3d78bdc'
down_revision: Union[str, None] = '62bd04b2fe33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
