"""add website_briefs table

Revision ID: 74e57bc2c2d5
Revises: 71761b9a3cf2
Create Date: 2026-08-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '74e57bc2c2d5'
down_revision: Union[str, None] = '71761b9a3cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_briefs',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('copy_direction', sa.Text(), nullable=False),
    sa.Column('design_direction', sa.Text(), nullable=False),
    sa.Column('site_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_briefs_business_id'), 'website_briefs', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_briefs_business_id'), table_name='website_briefs')
    op.drop_table('website_briefs')
    # ### end Alembic commands ###
