"""add opportunity_findings table

Revision ID: b8e3f61a7d92
Revises: a4d7e29c5f83
Create Date: 2026-08-26 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'b8e3f61a7d92'
down_revision: Union[str, None] = 'a4d7e29c5f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_findings',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.Enum('REVENUE_DROP', 'REVENUE_STREAK', 'TASK_OVERDUE', 'WEBSITE_NOT_CONNECTED', 'STRIPE_SYNC_STALE', name='opportunity_finding_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='opportunity_finding_severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_findings_business_id'), 'opportunity_findings', ['business_id'], unique=False)
    op.create_index(op.f('ix_opportunity_findings_detected_at'), 'opportunity_findings', ['detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_findings_detected_at'), table_name='opportunity_findings')
    op.drop_index(op.f('ix_opportunity_findings_business_id'), table_name='opportunity_findings')
    op.drop_table('opportunity_findings')
    # ### end Alembic commands ###
