"""add stripe_connections table and revenue_entries origin/stripe_charge_id

Revision ID: e7f4c82a91d3
Revises: c3d9a5e17b28
Create Date: 2026-08-22 00:00:04.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'e7f4c82a91d3'
down_revision: Union[str, None] = 'c3d9a5e17b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

revenue_entry_origin = postgresql.ENUM('MANUAL', 'STRIPE', name='revenue_entry_origin')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_connections',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_connections_business_id'), 'stripe_connections', ['business_id'], unique=True)

    revenue_entry_origin.create(op.get_bind(), checkfirst=True)
    op.add_column('revenue_entries', sa.Column('origin', revenue_entry_origin, nullable=False, server_default='MANUAL'))
    op.add_column('revenue_entries', sa.Column('stripe_charge_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_revenue_entries_stripe_charge_id'), 'revenue_entries', ['stripe_charge_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_entries_stripe_charge_id'), table_name='revenue_entries')
    op.drop_column('revenue_entries', 'stripe_charge_id')
    op.drop_column('revenue_entries', 'origin')
    revenue_entry_origin.drop(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_stripe_connections_business_id'), table_name='stripe_connections')
    op.drop_table('stripe_connections')
    # ### end Alembic commands ###
